<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Circular
 *
 * This model represents the 'circulars' table in the database.
 * It is used to store and manage company circular details.
 *
 * @package App\Models
 * @version 1.0.0
 *
 * Columns:
 *  - id (int) [Primary Key]
 *  - circular_no (string) [Unique Circular Number]
 *  - circular_name (string) [Unique Circular Title/Name]
 *  - circular_date (date) [Date of Circular Issue]
 *  - created_by (string) [User/Employee who created the circular]
 *  - file_path (string) [Path to the uploaded circular file]
 *  - created_at (timestamp) [Auto-generated by Laravel]
 *  - updated_at (timestamp) [Auto-generated by Laravel]
 *
 * Version Control Notes:
 *  - v1.0.0: Initial creation of the Circular model with mass-assignable fields.
 */
class Circular extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array<string>
     */
    protected $fillable = [
        'circular_no',
        'circular_name',
        'circular_date',
        'created_by',
        'file_path',
    ];
}
